spring:
  application:
    name: CodeControl-Backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/codecontrol1
    username: postgres
    password: postgres2024

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: harshitksinghai23@gmail.com
    password: mjwcnrutkwsgzmgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email

CodeControl-Backend:
  app:
    jwtCookieName: codecontrol-jwt
    jwtRefreshCookieName: codecontrol-jwt-refresh
    jwtSecret: codeControlSecretKey-12345678909876543212345678908765432123456789098761234567890
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 18000000
    refreshTokenSlidingWindowPeriod: 3600000

site:
  url: http://localhost:8080/api

#debug: true
